name: Playwright Test Run on Test Environment

on:
  workflow_dispatch:

jobs:
  test-on-test-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Create .env.test file
        run: |
          echo "BASE_URL=https://test.yourapp.com" >> .env.test
          echo "ADMIN_TOKEN=${{ secrets.ADMIN_TOKEN }}" >> .env.test

      - name: Run tests on Test environment
        run: npx playwright test

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
